import {test,expect} from '@playwright/test';
test('seller broadcasts, two phones join, one winner, outsider cannot control room',async({browser,request})=>{
  const created=await request.post('/api/rooms',{data:{name:'Vente du chaos',mode:'demo'}});
  expect(created.ok()).toBeTruthy();const {room,hostToken}=await created.json();
  const unauthorized=await request.post(`/api/rooms/${room.code}/start`,{data:{}});expect(unauthorized.status()).toBe(400);
  const hostContext=await browser.newContext({permissions:['camera','microphone']});
  await hostContext.addInitScript(({code,token})=>localStorage.setItem(`host:${code}`,token),{code:room.code,token:hostToken});
  const host=await hostContext.newPage();await host.goto(`/host/${room.code}`);
  await expect(host.getByRole('heading',{name:'Vente du chaos'})).toBeVisible();
  await host.getByRole('button',{name:'Activer la caméra'}).click();
  await expect(host.getByText('EN DIRECT',{exact:true})).toBeVisible();
  const buyerContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  const buyer=await buyerContext.newPage();await buyer.goto(`/join/${room.code}`);
  await expect(buyer.getByText('EN DIRECT',{exact:true})).toBeVisible();
  await expect.poll(async()=>await buyer.locator('.video-shell video').count()+await buyer.locator('.live-image').count()).toBeGreaterThan(0);
  const backupContext=await browser.newContext({viewport:{width:390,height:844}});
  await backupContext.addInitScript(()=>{Object.defineProperty(window,'RTCPeerConnection',{value:class{constructor(){throw new Error('WebRTC bloqué pour vérifier le secours');}}});});
  const backup=await backupContext.newPage();await backup.goto(`/join/${room.code}`);
  await expect(backup.locator('.live-image')).toBeVisible();
  await expect(backup.locator('.live-image')).toBeVisible();
  const frames=await backup.evaluate(()=>new Promise<number>(resolve=>{
    let count=0;const image=document.querySelector('.live-image')!;const observer=new MutationObserver(()=>count++);observer.observe(image,{attributes:true,attributeFilter:['src']});setTimeout(()=>{observer.disconnect();resolve(count);},1600);
  }));expect(frames).toBeGreaterThanOrEqual(8);
  await host.getByRole('button',{name:'Essayer avec un décor fictif'}).click();
  await expect(host.getByRole('heading',{name:'Trône du stagiaire suprême'})).toBeVisible();
  await host.getByRole('button',{name:'Lancer l’enchère'}).click();
  await expect(buyer.locator('.mobile-buy-dock button')).toBeEnabled();
  await buyer.getByLabel('Votre nom de collectionneur').fill('Alice du chaos');
  await buyer.screenshot({path:'test-results/mobile-live.png',fullPage:true});
  await host.screenshot({path:'test-results/host-live.png',fullPage:true});
  const before=await (await request.get(`/api/rooms/${room.code}`)).json();
  await buyer.locator('.mobile-buy-dock button').click();
  await expect(buyer.getByText('ADJUGÉ À ALICE DU CHAOS')).toBeVisible();
  await expect(host.getByText('ADJUGÉ À ALICE DU CHAOS')).toBeVisible();
  await expect(backup.getByText('ADJUGÉ À ALICE DU CHAOS')).toBeVisible();
  const late=await request.post(`/api/rooms/${room.code}/buy`,{data:{buyer:'Bob trop tard',lotId:before.active.id}});
  expect(late.status()).toBe(400);
  const final=await (await request.get(`/api/rooms/${room.code}`)).json();expect(final.active.buyer).toBe('Alice du chaos');expect(final.history).toHaveLength(1);
  await host.getByRole('button',{name:'Couper le live'}).click();
  await expect(buyer.getByText('EN ATTENTE',{exact:true})).toBeVisible();
  await backupContext.close();await buyerContext.close();await hostContext.close();
});
test('home works at desktop and mobile widths with no horizontal overflow',async({page})=>{
  await page.setViewportSize({width:1440,height:1000});await page.goto('/');
  await expect(page.getByRole('heading',{name:/Le luxe de/})).toBeVisible();
  await page.screenshot({path:'test-results/home-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'test-results/home-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.getByRole('button',{name:'Ouvrir ma salle'}).click();await expect(page.getByRole('dialog')).toBeVisible();
  await page.getByRole('button',{name:'Fermer',exact:true}).click();
  await page.getByLabel('Code de la salle').fill('FFFFFFFF');await page.getByRole('button',{name:'Entrer',exact:true}).click();
  await expect(page.locator('.home-error')).toContainText('Salle introuvable');
});

test('local vision model actually runs on the camera without any paid API',async({browser,request})=>{
  test.setTimeout(120000);
  const {room,hostToken}=await (await request.post('/api/rooms',{data:{name:'Test vision locale',mode:'demo'}})).json();
  const context=await browser.newContext({permissions:['camera']});
  await context.addInitScript(({code,token})=>localStorage.setItem(`host:${code}`,token),{code:room.code,token:hostToken});
  const page=await context.newPage();await page.goto(`/host/${room.code}`);
  await page.getByRole('button',{name:'Activer la caméra'}).click();
  await expect(page.getByText('EN DIRECT',{exact:true})).toBeVisible();
  const responsePromise=page.waitForResponse(r=>r.url().endsWith(`/api/rooms/${room.code}/scan`),{timeout:90000});
  await page.getByRole('button',{name:'Sélectionner 7 objets'}).click();
  const response=await responsePromise;
  const input=response.request().postDataJSON();
  expect(input.source).toBe('local');expect(Array.isArray(input.candidates)).toBeTruthy();
  // La caméra synthétique de Chromium ne montre aucun objet : la sélection est complétée par des matériaux absurdes.
  expect(response.ok()).toBeTruthy();expect((await response.json()).count).toBe(7);
  await context.close();
});

test('phone is the camera while the PC remains the authorized auction host',async({browser,request})=>{
  const {room,hostToken}=await (await request.post('/api/rooms',{data:{name:'Téléphone caméra',mode:'demo'}})).json();
  const denied=await request.get(`/api/rooms/${room.code}/camera-access`);expect(denied.status()).toBe(400);
  const {cameraToken}=await (await request.get(`/api/rooms/${room.code}/camera-access`,{headers:{Authorization:`Bearer ${hostToken}`}})).json();
  const cameraCannotSell=await request.post(`/api/rooms/${room.code}/start`,{headers:{Authorization:`Bearer ${cameraToken}`},data:{}});expect(cameraCannotSell.status()).toBe(400);
  const hostContext=await browser.newContext();await hostContext.addInitScript(({code,token})=>localStorage.setItem(`host:${code}`,token),{code:room.code,token:hostToken});
  const host=await hostContext.newPage();await host.goto(`/host/${room.code}`);
  await host.getByRole('button',{name:'Filmer avec mon téléphone'}).click();await expect(host.getByRole('heading',{name:'Filmez depuis votre téléphone.'})).toBeVisible();
  const cameraContext=await browser.newContext({permissions:['camera'],viewport:{width:390,height:844}});const camera=await cameraContext.newPage();await camera.goto(`/camera/${room.code}#${cameraToken}`);
  await camera.getByRole('button',{name:'Démarrer la caméra du téléphone'}).click();
  await expect(host.getByText('CAMÉRA DU TÉLÉPHONE',{exact:true})).toBeVisible();
  await expect(host.getByRole('button',{name:'Sélectionner 7 objets'})).toBeEnabled();
  const scan=host.waitForResponse(r=>r.url().endsWith(`/api/rooms/${room.code}/scan`),{timeout:45000});await host.getByRole('button',{name:'Sélectionner 7 objets'}).click();
  const response=await scan;expect(response.request().postDataJSON().source).toBe('local');
  expect(response.ok()).toBeTruthy();expect((await response.json()).count).toBe(7);
  await host.getByRole('button',{name:'Couper le téléphone'}).click();await expect(camera.getByText('CAMÉRA ÉTEINTE',{exact:true})).toBeVisible();
  await cameraContext.close();await hostContext.close();
});
