'use client';
import {useRef,useState} from 'react';
import type {Candidate} from '@/lib/types';
export function DetailPicker({image,onClose,onSave,busy}:{image:string;onClose:()=>void;onSave:(candidate:Candidate)=>void;busy:boolean}){
  const [label,setLabel]=useState('Petit trésor');const [box,setBox]=useState<Candidate['bbox']>([.35,.35,.3,.3]);
  const start=useRef<[number,number]|null>(null);
  function point(e:React.PointerEvent<HTMLDivElement>):[number,number]{const r=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];}
  return <div className="modal-backdrop"><section className="modal detail-modal" role="dialog" aria-modal="true" aria-labelledby="detail-title"><button className="icon-button close" aria-label="Fermer le cadrage" onClick={onClose}>×</button><span className="eyebrow">SÉLECTION ASSISTÉE · IMAGE FIGÉE</span><h2 id="detail-title">Même la dernière miette.</h2><p className="muted small">Tracez un cadre autour du détail, puis nommez-le. Ce cadrage manuel complète les objets que l’IA ne reconnaît pas.</p><div className="detail-canvas" onPointerDown={e=>{start.current=point(e);e.currentTarget.setPointerCapture(e.pointerId);setBox([start.current[0],start.current[1],.001,.001]);}} onPointerMove={e=>{if(!start.current)return;const p=point(e),a=start.current;setBox([Math.min(a[0],p[0]),Math.min(a[1],p[1]),Math.abs(p[0]-a[0]),Math.abs(p[1]-a[1])]);}} onPointerUp={()=>{start.current=null;}} onPointerCancel={()=>{start.current=null;}}><img src={image} alt="Image figée à cadrer" draggable={false}/><span style={{left:`${box[0]*100}%`,top:`${box[1]*100}%`,width:`${box[2]*100}%`,height:`${box[3]*100}%`}}/></div><label>Nom de l’objet<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={50}/></label><button className="button primary full" disabled={busy||!label.trim()||box[2]<.015||box[3]<.015} onClick={()=>onSave({label:label.trim().toLowerCase(),bbox:box,confidence:1,person:false})}>Ajouter ce détail à la sélection</button></section></div>;
}
